Fixed error correction in multi-block symbols

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19247,6 +19247,210 @@ ac_config_headers="$ac_config_headers config.h"
 ac_config_files="$ac_config_files Makefile util/Makefile util/dmtxquery/Makefile util/dmtxread/Makefile util/dmtxwrite/Makefile test/Makefile test/test_opengl/Makefile test/test_simple/Makefile test/test_unit/Makefile"
 
 
+if test "${ac_cv_header_tiff_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for tiff.h" >&5
+echo $ECHO_N "checking for tiff.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_tiff_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_tiff_h" >&5
+echo "${ECHO_T}$ac_cv_header_tiff_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking tiff.h usability" >&5
+echo $ECHO_N "checking tiff.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <tiff.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking tiff.h presence" >&5
+echo $ECHO_N "checking tiff.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <tiff.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: tiff.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: tiff.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tiff.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: tiff.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: tiff.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: tiff.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tiff.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: tiff.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tiff.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: tiff.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tiff.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: tiff.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tiff.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: tiff.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tiff.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: tiff.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## -------------------------------------- ##
+## Report this to mike@dragonflylogic.com ##
+## -------------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for tiff.h" >&5
+echo $ECHO_N "checking for tiff.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_tiff_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_tiff_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_tiff_h" >&5
+echo "${ECHO_T}$ac_cv_header_tiff_h" >&6; }
+
+fi
+if test $ac_cv_header_tiff_h = yes; then
+  { echo "$as_me:$LINENO: checking for TIFFReadScanline in -ltiff" >&5
+echo $ECHO_N "checking for TIFFReadScanline in -ltiff... $ECHO_C" >&6; }
+if test "${ac_cv_lib_tiff_TIFFReadScanline+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ltiff  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char TIFFReadScanline ();
+int
+main ()
+{
+return TIFFReadScanline ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_tiff_TIFFReadScanline=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_tiff_TIFFReadScanline=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_tiff_TIFFReadScanline" >&5
+echo "${ECHO_T}$ac_cv_lib_tiff_TIFFReadScanline" >&6; }
+if test $ac_cv_lib_tiff_TIFFReadScanline = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBTIFF 1
+_ACEOF
+
+fi
+
+fi
+
+
+
 
 for ac_header in sys/time.h
 do
